version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  web:
    image: centos:7.2.1511
    ports:
      - "80:80"
      - "443:443"
    # command requires dumb-init to be installed, entrypoint can't be used since
    # it's used during ansible install
    command: ["/usr/local/bin/dumb-init", "/usr/sbin/nginx", "-g", "daemon off;"]
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
  #
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx   
